### ISSUE TITLE
Usage with Next.js

### ISSUE THREAD

**Issue by birksy89** [aperturerobotics/react-chonky#64]
Hello, thanks for forking this and keeping it updated...

I have just managed to get this working in my project, but I'm not sure if it's done in the best way.

I had to import the library "dynamically" as it was complaining about ESM:

```
⨯ Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Andrew\Desktop\Projects\_Client\node_modules\react-dnd\dist\index.js from C:\Users\Andrew\Desktop\Projects\_Client\node_modules\@aperturerobotics\chonky\dist\chonky.cjs.development.js not supported.
Instead change the require of index.js in C:\Users\Andrew\Desktop\Projects\_Client\node_modules\@aperturerobotics\chonky\dist\chonky.cjs.development.js to a dynamic import() which is available in all CommonJS modules.
```

I got it working by adding it like this:

```
  const FullFileBrowser = dynamic(
    () => import("@aperturerobotics/chonky").then((mod) => mod.FullFileBrowser),
    { ssr: false }
  );

  const ChonkyIconFA = dynamic(
    () =>
      import("@aperturerobotics/chonky-icon-fontawesome").then(
        (mod) => mod.ChonkyIconFA
      ),
    { ssr: false }
  );
```

Any advice would be greatly appreciated, thanks again!

**Comment by birksy89** [comment]
Haha, I'm glad I commented then - I almost just moved on with my day.

I didn't start with the original "Chonky" - I just spotted that people said that this fork existed and was more recently updated, so chose this.

I've just this second tried to add a custom action as defined here:
https://chonky.io/docs/2.x/file-actions/custom-actions

But I couldn't get it to work "dynamically" - So I've also now installed the original Chonky, just to get this working.

Was there a reason you moved away from the original Chonky? I was just wondering if I'd made a mistake choosing this version ?

Maybe for my needs the basic/original one would work fine?

**Comment by oliverlevay** [comment]
So I'm trying to upgrade my version of Next.js. We use MUI in our project, but things get really funky with a newer version of material ui and chonky. So right now we have both mui v4 and the old material-ui as dependencies in our project, which is not very good. You can see it in actions on our website 

[https://www.dsek.se/photos](https://www.dsek.se/photos
)

I'm trying to import other things like ChonkyActions and FileHelper but I just can't get it to work.

**Comment by paralin** [comment]
@oliverlevay @birksy89 There seem to be both cjs and esm versions in dist/. I'm not familiar with the "dts" build system used here. Might migrate off of it to esbuild instead soon.

**Comment by paralin** [comment]
Using esbuild now. It should work!

**Comment by Konard** [comment]
@paralin I still get that error for 0.3.0 version.

```
konard@MBP-Konstantin material-ui-nextjs % yarn build
yarn run v1.22.22
$ next build
  ▲ Next.js 14.2.5

   Creating an optimized production build ...
Failed to compile.

./node_modules/@aperturerobotics/chonky/dist/chonky.cjs.production.min.js
Module not found: ESM packages (react-dnd) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@aperturerobotics/chonky/dist/index.js
./src/app/about/page.js

./node_modules/@aperturerobotics/chonky/dist/chonky.cjs.production.min.js
Module not found: ESM packages (react-dnd-html5-backend) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@aperturerobotics/chonky/dist/index.js
./src/app/about/page.js


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
konard@MBP-Konstantin material-ui-nextjs % 
```

**Comment by paralin** [comment]
@Konard is react-dnd in your package.json?

**Comment by paralin** [comment]
Ok I think I see the issue. Will fix today!

**Comment by Konard** [comment]
@paralin 

I use this one as a basis: https://github.com/mui/material-ui/tree/master/examples/material-ui-nextjs 

I tried to add `"react-dnd": "latest",` but it did'nt help.

On an `about` page, I've added:

```js
import { FullFileBrowser } from '@aperturerobotics/chonky';
import { ChonkyIconFA } from '@aperturerobotics/chonky-icon-fontawesome';
```

and

```js
const files = [null, null, null, null, null];
```

and

```js
        <FullFileBrowser
          files={files}
          iconComponent={ChonkyIconFA}
          disableDragAndDrop={true}
        />
```

I also tried to use

```
const FullFileBrowser = dynamic(
  () => import("@aperturerobotics/chonky").then((mod) => mod.FullFileBrowser),
  { ssr: false }
);

const ChonkyIconFA = dynamic(
  () =>
    import("@aperturerobotics/chonky-icon-fontawesome").then(
      (mod) => mod.ChonkyIconFA
    ),
  { ssr: false }
);
```

as a workaround, it didn't work.

**Comment by Konard** [comment]
@paralin 

I have added a complete example:

https://github.com/Konard/mui-nextjs-chonky?tab=readme-ov-file#chonky-problem

The only file code file is changed https://github.com/Konard/mui-nextjs-chonky/blob/main/src/app/about/page.js, other files are the same as in example: https://github.com/mui/material-ui/tree/master/examples/material-ui-nextjs

Error changes depending on presence `'use client'` but in both cases it does not work.

**Comment by Konard** [comment]
Strange, but original chonky being written in mui 4 works with mui 5 just fine... 

https://github.com/Konard/mui-nextjs-chonky/blob/original-chonky/README.md#original-chonky-version-works-with-mui-v5-but-it-uses-mui-v4

https://github.com/Konard/mui-nextjs-chonky/pull/1/files#diff-adcd2b19a1874e3ea70ae26196110f1f4ba70fcf27cf3fe855e5a610a9993a91

The whole reason I was looking for mui v5 support was the assumption that mui v4 with not work with mui v5, but it works..

Well, still it would be nice to have mui v5 support without the need to use mui v4 at all.

**Comment by paralin** [comment]
Thanks for checking into this. I'll try to fix this pkg as soon as I have a chance.

**Comment by paralin** [comment]
I believe this was fixed, feel free to let me know if not.
