### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by pbenard73** [aperturerobotics/react-chonky#71]
Hi.

Since Main repository is not maintained anymore, I and many other people use your repo as best alternative.

However, I'd like to do some contributions. 

Issue is when I want to run the stack as mentionned in this famous 'contributing.md'...

Do you think you could get some times in order to update the way other people can contribute in creating the workspace as mentioned ? 

Thanks for your time and all your works even done.

**Comment by paralin** [comment]
Hi,

I dropped Contributing.md and added a basic guide to README.

Also fixed various build issues & updated the deps.

Hopefully that helps!
