### ISSUE TITLE
Is there a loading state available?

### ISSUE THREAD

**Issue by jcvegan** [aperturerobotics/react-chonky#75]
First thanks for the time and effort done on mantaining this package. I appreciate it a lot.

Just I would like to know if there is a loading state available?

Thanks :)

**Comment by paralin** [comment]
I see under FileBrowserProps => files

```
  /**
   * List of files that will be displayed in the main container. The provided value
   * **must** be an array, where each element is either `null` or an object that
   * satisfies the `FileData` type. If an element is `null`, a loading placeholder
   * will be displayed in its place.
   */
  files: FileArray;
```

So, pass a list of null to files to show a loading indicator.

:)
